[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  port = 8888
  functionsPort = 9999

[[functions]]
  schedule = "0 0 1 * *"  # 毎月1日 0:00 (UTC) = 日本時間 9:00
  path = "netlify/functions/reset-usage.ts"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"